/* Index page
  This is where the user can search for movies
*/

import Head from 'next/head'
import { FaSearch } from 'react-icons/fa'
import { useState } from 'react'
import Link from 'next/link'


export default function Home() {
  const [data, setData] = useState([]);

  const handleChange = (e) => {
    let search = e.target.value;
    console.log(search);

    /* If something is typed in the search bar, 
    - fetch api-data and set data to an array of ten results.
    If nothing is typed, set data to an empty array
    */
    !search == '' ? (
      fetch(`https://api.themoviedb.org/3/search/movie?api_key=2e28a26a70c14a7b5e9a16e05864446a&language=en-US&query=${search}&page=1`)
      .then((res) => res.json())
      .then((data) => {
        setData(data.results.slice(0,10))
        console.log(data);
      })
    ) : (
      setData([])
    )
  }


  return (
    <div className='text-center relative top-[15vh]'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-col min-h-full'>
        {/* Search header */}
        <h1 className="text-white font-bold text-6xl sm:text-8xl  ">
          Search for a movie!
        </h1>

        <div className='mt-12'>
          <form className='flex justify-center'>
            <div className='group'>

              {/* Search inputbar */}
              <input
                className='rounded-r-none w-full sm:w-96 peer'
                type="text"
                onChange={(e) => handleChange(e)}
                placeholder='Search for a movie here...'
              />

              {/* If something is typed - show ul of results */}
              { data.length ?
                <ul className='sm:w-96 mt-2 bg-white text-black rounded-b-3xl text-left p-2 px-4 invisible active:visible peer-focus:visible group-focus:visible'>
                  { data.map((movie) => 
                    <Link href={`/movies/${movie.id}`} key={movie.id}>
                      <a>
                        <li className='mb-2 hover:text-gray-400'>{movie.title}</li>
                      </a>
                    </Link>
                  )}
                </ul> 
                :
                ''
              }
            </div>

            {/* Search icon */}
            <div className='rounded-r-full p-3 h-fit drop-shadow-lg bg-[#E87F4A]'><FaSearch /></div>
          </form>
        </div>
      </main>
    </div>
  )
}
